apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: airepubliq
type: Opaque
stringData:
  flask-env: "production"
  database-url: "postgresql://airepublic:CHANGE_THIS@postgres-service.airepubliq.svc.cluster.local:5432/ai_refinement_v2"
  redis-url: "redis://redis-service.airepubliq.svc.cluster.local:6379/0"
  secret-key: "CHANGE_THIS_TO_A_RANDOM_SECRET_KEY_IN_PRODUCTION"
