apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: airepubliq
type: Opaque
stringData:
  postgres-db: "ai_refinement_v2"
  postgres-user: "airepublic"
  postgres-password: "CHANGE_THIS_IN_PRODUCTION"
